'''
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
'''
list1=[]
list2=[]
for i in t:
    list1.append(i)
for i in s:
    list2.append(i)
for i in list2:
    if i in t:
        list1.remove(i)
return list1[0]